version: "3.5"

services:
    web:
        build: .
        container_name: parser_telegram_bot
        ports:
            - "5000:5000"
        env_file:
            - .env
        stdin_open: true
        tty: true